# Everforest dark/hard — matched to everbar.
[main]
font=monospace:size=9
terminal=foot
icons-enabled=no
prompt="> "
lines=8
width=24
horizontal-pad=16
vertical-pad=4
inner-pad=6

[colors]
background=272e33ff
text=d3c6aaff
prompt=a7c080ff
input=d3c6aaff
match=dbbc7fff
selection=374145ff
selection-text=d3c6aaff
selection-match=dbbc7fff
border=a7c080ff

[border]
width=2
radius=0
selection-radius=0
